#!/bin/bash

OC_GP_OKTA="$HOME/dev/openconnect-gp-okta"
PYTHON="$OC_GP_OKTA/venv/bin/python"

$PYTHON $OC_GP_OKTA/openconnect-gp-okta \
    --username cory.heuschkel@smartthings.com \
    --sudo mplsvpn.smartthings.com
