font:
  normal:
    family: mononoki
  size: 10.5
colors:
  primary:
    background: '#000000'
selection:
  save_to_clipboard: true
key_bindings:
  - key: F11
    command:
      program: "wmctrl"
      args: ["-r", ":ACTIVE:", "-b", "toggle,fullscreen"]
  # Eat desktop switching commands to avoid vim doing bad things to the file
  # being edited
  - key: Left
    mods: Control|Alt
    action: None
  - key: Right
    mods: Control|Alt
    action: None
