font:
  normal:
    family: mononoki
  size: 12.0
selection:
  save_to_clipboard: true
key_bindings:
  - key: F11
    command:
      program: "wmctrl"
      args: ["-r", ":ACTIVE:", "-b", "toggle,fullscreen"]
